-- CreateTable
CREATE TABLE "neraca_bank" (
    "id_pelapor" TEXT NOT NULL,
    "periode_laporan" TEXT NOT NULL,
    "periode_data" TEXT NOT NULL,
    "id" TEXT NOT NULL,
    "pos_laporan_keuangan" TEXT NOT NULL,
    "deskripsi_pos_laporan_keuangan" TEXT NOT NULL,
    "cakupan_data" TEXT NOT NULL,
    "deskripsi_cakupan_data" TEXT NOT NULL,
    "nominal_rupiah" DOUBLE PRECISION NOT NULL,
    "nominal_valas" DOUBLE PRECISION NOT NULL,
    "nominal_valas_usd" DOUBLE PRECISION,
    "nominal_valas_non_usd" DOUBLE PRECISION,
    "nominal_total" DOUBLE PRECISION NOT NULL,
    "nominal_perusahaan_induk_rupiah" DOUBLE PRECISION,
    "nominal_perusahaan_induk_valas" DOUBLE PRECISION,
    "nominal_perusahaan_induk_total" DOUBLE PRECISION,
    "nominal_perusahaan_anak_selain_asuransi_rupiah" DOUBLE PRECISION,
    "nominal_perusahaan_anak_selain_asuransi_valas" DOUBLE PRECISION,
    "nominal_perusahaan_anak_selain_asuransi_total" DOUBLE PRECISION,
    "nominal_perusahaan_anak_asuransi_rupiah" DOUBLE PRECISION,
    "nominal_perusahaan_anak_asuransi_valas" DOUBLE PRECISION,
    "nominal_perusahaan_anak_asuransi_total" DOUBLE PRECISION,
    "nominal_konsolidasi_rupiah" DOUBLE PRECISION,
    "nominal_konsolidasi_valas" DOUBLE PRECISION,
    "nominal_konsolidasi_total" DOUBLE PRECISION,
    "buk" TEXT NOT NULL,
    "bus" TEXT NOT NULL,
    "uus" TEXT NOT NULL,
    "kategori" TEXT NOT NULL,

    CONSTRAINT "neraca_bank_pkey" PRIMARY KEY ("pos_laporan_keuangan")
);
